// web/src/pages/blog/detail/index.tsx
import React, { useState, useEffect } from 'react';
import { IndexModelState, ConnectRC, connect } from 'umi';
import './index.less';
import Vditor from 'vditor'
import "../../../styles/vditor.css"
import "../../../styles/vditor.less"
import Praise from "./components/praise.tsx"
import { Button } from 'antd';
import { createFromIconfontCN } from '@ant-design/icons';
const IconFont = createFromIconfontCN({
    scriptUrl: '//at.alicdn.com/t/font_1762601_mkiqfjs1yth.js',
});
interface PageProps {
    index: IndexModelState;
    loading: boolean;
}

const Detail: ConnectRC<PageProps> = ({ index, dispatch }) => {
    useEffect(() => {
        Vditor.preview(document.getElementById("htmlView"), markdownContent, {
            speech: {
                enable: true,
            },
            anchor: true,
            hljs: {
                enable: true,
                lineNumber: true,
                style: "native"
            },
            markdown: {
                toc: true
            },
            transform: (html: string) => {
                let arr: { children: { id: (element: ChildNode, id: any, firstChild: ChildNode | null) => any; title: ChildNode | null; children: never[]; }[]; }[] = []
                parseDom(html).forEach(element => {
                    if (element.nodeName == "H1" || element.nodeName == "H2" || element.nodeName == "H3") {
                        let obj = { id: element.id, title: element.firstChild, children: [] }
                        if (element.nodeName == "H1") {
                            arr.push(obj)
                        }
                        if (element.nodeName == "H2") {
                            arr[arr.length - 1].children.push(obj)
                        }
                    }
                })
                console.log(arr)
                return html
            }
        })
    }, [])
    const { name } = index;
    const { count } = index;
    const [visible, setVisible] = useState(false)
    const parseDom = (arg: any) => {
        let objE = document.createElement("div");
        objE.innerHTML = arg;
        return objE.childNodes;
    }
    const editTitle = () => {
        dispatch({
            type: "index/save"
        })
    }
    const [markdownContent] = useState('# P01:课程介绍和环境搭建\n' +
        '[ **M** ] arkdown + E [ **ditor** ] = **Mditor**  \n' +
        '> Mditor 是一个简洁、易于集成、方便扩展、期望舒服的编写 markdown 的编辑器，仅此而已... \n\n' +

        '**这是加粗的文字**\n\n' +
        '*这是倾斜的文字*`\n\n' +
        '***这是斜体加粗的文字***\n\n' +
        '~~这是加删除线的文字~~ \n\n' +
        '\`console.log(111)\` \n\n' +
        '# p02:来个Hello World 初始Vue3.0\n' +
        '> aaaaaaaaa\n' +
        '>> bbbbbbbbb\n' +
        '>>> cccccccccc\n' +
        '***\n\n\n' +
        '# p03:Vue3.0基础知识讲解\n' +
        '> aaaaaaaaa\n' +
        '>> bbbbbbbbb\n' +
        '>>> cccccccccc\n\n' +
        '# p04:Vue3.0基础知识讲解\n' +
        '> aaaaaaaaa\n' +
        '>> bbbbbbbbb\n' +
        '>>> cccccccccc\n\n' +
        '#5 p05:Vue3.0基础知识讲解\n' +
        '> aaaaaaaaa\n' +
        '>> bbbbbbbbb\n' +
        '>>> cccccccccc\n\n' +
        '# p06:Vue3.0基础知识讲解\n' +
        '> aaaaaaaaa\n' +
        '>> bbbbbbbbb\n' +
        '>>> cccccccccc\n\n' +
        '# p07:Vue3.0基础知识讲解\n' +
        '> aaaaaaaaa\n' +
        '>> bbbbbbbbb\n' +
        '>>> cccccccccc\n\n' +
        '``` var a=11; ```'
    )
    return <div className="detail" onClick={editTitle}>
        <div className="detail-title">
            <div className="detail-title-top">
                <h1>这是文章的标题</h1>
                <div>
                    <IconFont type="uv-caret-forward-circle-outline" className="detail-title-top-icon" />
                    {/* <IconFont type="uv-pause-circle-outline" /> */}
                    <IconFont type="uv-book-outline" className="detail-title-top-icon" />
                    <IconFont type="uv-print-outline" className="detail-title-top-icon" />
                </div>
            </div>
            <div>
                <IconFont
                    type="uv-person-outline"
                    className="list-normal-bottom-iconO"
                />
                <span>作者</span>
                <IconFont
                    type="uv-time-outline"
                    className="list-normal-bottom-icon"
                />
                <span>2020年10月1日</span>
                <IconFont
                    type="uv-chatbubble-outline"
                    className="list-normal-bottom-icon"
                />
                <span>1220条评论</span>
                <IconFont
                    type="uv-eye-outline"
                    className="list-normal-bottom-icon"
                />
                <span>1220次浏览</span>
                <IconFont
                    type="uv-information-outline"
                    className="list-normal-bottom-icon"
                />
                <span>122字数</span>
            </div>
        </div>
        <div style={{ backgroundImage: `url(https://gitee.com/Uvdream/images/raw/master/images/20200806150710.png)` }} className="detail-img"></div>
        <div id="htmlView" className="detail-content"></div>
        <div className="detail-praise">
            <div className="detail-praise-time">
                <section>
                    <IconFont
                        type="uv-time-outline"

                    />
                    最后修改时间:2020年10月1日</section>
                <section>
                    <IconFont
                        type="uv-alert-circle-outline"

                    />
                    允许转载</section>
            </div>
            <div className="detail-praise-text">
                <Button type="primary" danger shape="round" onClick={() => { setVisible(true) }} >
                    <IconFont type="uv-wallet-outline" />
                    赞赏</Button>
                <p>如果觉得我的文章对你有用，请随意赞赏</p>
            </div>
        </div>
        <div className="detail-btn">
            <Button shape="round" >
                上一篇</Button>
            <Button shape="round" >
                下一篇</Button>
        </div>
        <Praise visible={visible} changeVisible={() => { setVisible(false) }} />
        {/* <div>
            Hello {name}
            <p onClick={() => { dispatch({ type: 'index/add' }) }}>{count}</p>
        </div> */}
    </div>;
};
export default connect(({ index }: { index: IndexModelState }) => ({
    index,
}))(Detail);

// my-app/src/app/blog/detail/detail.component.ts
import { Component, OnInit, ViewChild } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { ArticleService } from '../../service/article.service';
import { ArticleCatalogService } from '../../service/article-catalog.service';
import { Title } from '@angular/platform-browser';

interface TabItem {
  id: number;
  title: string;
  imgUrl: string;
}
@Component({
  selector: 'app-detail',
  templateUrl: './detail.component.html',
  styleUrls: ['./detail.component.less'],
})
export class DetailComponent implements OnInit {
  constructor(
    private route: ActivatedRoute,
    private request: ArticleService,
    private articleCat: ArticleCatalogService,
    private titleService: Title
  ) { }
  // 文章标题
  public title: string;
  // html内容
  public htmlContent: any;
  // markdown内容
  public markDown: any;
  // 作者
  public author: string;
  // 时间
  public time: string;
  // 文章字数
  public wordCount: string;
  // 浏览次数
  public viewCount: string;
  // 评论数
  public commentCount: string;
  // 图片
  public topImg: string;
  @ViewChild('vditor') myDom: HTMLDivElement;
  isVisible = false;
  public tabList = [
    {
      id: 1,
      title: '支付宝支付',
      imgUrl:
        'https://gitee.com/Uvdream/images/raw/master/images/20200812100455.png',
    },
    {
      id: 2,
      title: '微信支付',
      imgUrl:
        'https://gitee.com/Uvdream/images/raw/master/images/20200812100455.png',
    },
  ];
  public imgUrl = this.tabList[0].imgUrl;
  public activeId = this.tabList[0].id;
  ngOnInit(): void {
    let id = '';
    let password = '';
    this.route.queryParams.subscribe((params) => {
      id = params.id;
      password = params.password;
      if (password === undefined) {
        password = '';
      }
    });
    this.getDetail(id, password);
    this.viewArticle(id);
  }
  // 获取文章详情
  getDetail = async (id, password) => {
    const res = await this.request.getDetail({ id, password });
    if (res.code !== 200) {
      return;
    }
    this.htmlContent = res.data.article_html;
    this.markDown = res.data.article_content;
    // console.log(res.data);
    this.title = res.data.title;
    this.author = res.data.user_name;
    this.time = res.data.UpdatedAt;
    this.wordCount = res.data.word_count;
    this.viewCount = res.data.view_count;
    this.commentCount = res.data.comment_count;
    this.topImg = res.data.img_url;
    this.setTitle(this.title + '(汪中杰的个人博客)');
    const mainElement = document.getElementById('vditor') as HTMLDivElement;
    import('vditor').then((Vditor: any) =>
      Vditor.preview(mainElement, this.markDown, {
        speech: {
          enable: true,
        },
        anchor: 0,
        hljs: {
          enable: true,
          lineNumber: true,
          style: 'native',
        },
        markdown: {
          toc: true,
        },
        transform: (html: string) => {
          const arr = [];
          this.parseDom(html).forEach((element) => {
            if (
              element.nodeName === 'H1' ||
              element.nodeName === 'H2' ||
              element.nodeName === 'H3'
            ) {
              const obj = {
                // tslint:disable-next-line:no-string-literal
                id: element['id'],
                // tslint:disable-next-line:no-string-literal
                title: element['innerText'],
                name: element.nodeName,
                children: [],
              };
              arr.push(obj);
              // if (element.nodeName === 'H1') {
              //   arr.push(obj);
              // }
              // if (element.nodeName === 'H2') {
              //   arr[arr.length - 1].children.push(obj);
              // }
              // if (element.nodeName === 'H3') {
              //   arr[arr.length - 1].children[
              //     arr[arr.length - 1].children.length - 1
              //   ].children.push(obj);
              // }
            }
          });
          this.articleCat.SetCatLog(arr);

          return html;
        },
      })
    );
  }
  parseDom = (arg: any) => {
    const objE = document.createElement('div');
    objE.innerHTML = arg;
    return objE.childNodes;
  }
  showModal = (data: boolean) => {
    this.isVisible = data;
  }
  tabClick = (data: TabItem) => {
    this.activeId = data.id;
  }
  public setTitle = (newTitle: string) => {
    this.titleService.setTitle(newTitle);
  }
  async viewArticle(id: string): Promise<void> {
    console.log('文章访问');
    const res = await this.request.viewBlog(id);
  }
}

<div class="detail">
  <!-- 上面 -->
  <div class="detail-title">
    <div class="detail-title-top">
      <h1>{{ title }}</h1>
      <div>
        <span
          class="iconfont uv-caret-forward-circle-outline margin-left-right-5"
        ></span>
        <span class="iconfont uv-book-outline margin-left-right-5"></span>
        <span class="iconfont uv-print-outline margin-left-right-5"></span>
      </div>
    </div>
    <div>
      <span class="iconfont uv-person-outline" style="margin: 0 5px 0 0"></span>

      <span>{{ author }}</span>

      <span
        class="iconfont uv-time-outline"
        style="margin: 0 5px 0 10px"
      ></span>
      <span>{{ time| date:"y-d-MM HH:mm:ss " }}</span>
      <span
        class="iconfont uv-chatbubble-outline"
        style="margin: 0 5px 0 10px"
      ></span>
      <span>{{ commentCount }}条评论</span>
      <span class="iconfont uv-eye-outline" style="margin: 0 5px 0 10px"></span>
      <span>{{ viewCount }}次浏览</span>
      <span
        class="iconfont uv-information-outline"
        style="margin: 0 5px 0 10px"
      ></span>
      <span>{{ wordCount }}字数</span>
    </div>
  </div>
  <!-- 图片 -->
  <div
    class="detail-img"
    [ngStyle]="{
      'background-image': 'url(' + topImg + ')'
    }"
  ></div>
  <div #vditor id="vditor" class="detail-content"></div>
  <div [innerHTML]="htmlContent" style="display: none"></div>
  <div class="detail-praise">
    <div class="detail-praise-time">
      <section>
        <span class="iconfont uv-time-outline"></span>
        最后修改时间:2020年10月1日
      </section>
      <section>
        <span class="iconfont uv-alert-circle-outline"></span>
        允许转载
      </section>
    </div>
    <div class="detail-praise-text">
      <button
        nz-button
        nzType="primary"
        nzShape="round"
        nzDanger
        (click)="showModal(true)"
      >
        赞赏
      </button>
      <p>如果觉得我的文章对你有用，请随意赞赏</p>
    </div>
  </div>
  <nz-modal
    [(nzVisible)]="isVisible"
    nzTitle="赞赏作者"
    [nzContent]="modalContent"
    [nzFooter]="modalFooter"
    nzWidth="400"
    (nzOnCancel)="showModal(false)"
  >
    <ng-template #modalContent>
      <div class="detail-modal-img">
        <div class="detail-modal-img-tab">
          <section
            *ngFor="let item of tabList"
            (click)="tabClick(item)"
            [ngClass]="{ active: activeId == item.id }"
          >
            {{ item.title }}
          </section>
        </div>
        <img [src]="imgUrl" alt="" />
      </div>
    </ng-template>
    <ng-template #modalFooter>
      <div class="detail-modal-footer">
        <button
          nz-button
          nzType="primary"
          nzShape="round"
          (click)="showModal(false)"
        >
          确认
        </button>
      </div>
    </ng-template>
  </nz-modal>
  <div class="detail-btn">
    <button nz-button nzType="default" nzShape="round">上一篇</button>
    <button nz-button nzType="default" nzShape="round">下一篇</button>
  </div>
</div>
