// web/src/layouts/components/right-content/blog-message.tsx
import React from 'react';
import "./index.less"
import { createFromIconfontCN } from '@ant-design/icons';
const IconFont = createFromIconfontCN({
    scriptUrl: '//at.alicdn.com/t/font_1762601_mkiqfjs1yth.js',
});
const BlogMessage = () => {
    return (
        <div className="message">
            <div className="message-title">
                博客信息
            </div>
            <div className="message-content">
                <section>
                    <div>
                        <IconFont type="uv-ribbon-outline" className="message-content-icon" />
                        文章数目
                    </div>
                    <div className="message-tag">
                        200
                    </div>
                </section>
                <section>
                    <div>
                        <IconFont type="uv-chatbubble-outline" className="message-content-icon" />
                        评论数量
                    </div>
                    <div className="message-tag" >
                        100
                    </div>
                </section>
                <section>
                    <div>
                        <IconFont type="uv-browsers-outline" className="message-content-icon" />
                        运行天数
                    </div>
                    <div className="message-tag">
                        4年7天
                    </div>
                </section>
                <section>
                    <div>
                        <IconFont type="uv-pulse-outline" className="message-content-icon" />
                        最后活动
                    </div>
                    <div className="message-tag">4天前</div>
                </section>
            </div>
        </div>
    )
}
export default BlogMessage

// web/src/app/blog/home/component/right-content/blog-message/blog-message.component.ts
import { Component, OnInit } from '@angular/core';
import { BlogConfigService } from '@service/blog-config.service';
@Component({
  selector: 'app-blog-message',
  templateUrl: './blog-message.component.html',
  styleUrls: ['./blog-message.component.less']
})
export class BlogMessageComponent implements OnInit {

  constructor(public config: BlogConfigService) { }

  ngOnInit(): void {
  }

}

<div class="message">
  <div class="message-title">博客信息</div>
  <div class="message-content">
    <section>
      <div>
        <!-- <span class="iconfont uv-ribbon-outline"></span> -->
        <svg aria-hidden="true">
          <use xlink:href="#icon-xunzhang"></use>
        </svg>
        文章数目
      </div>
      <div class="message-tag">{{config.ArticleCount}}</div>
    </section>
    <section>
      <div>
        <!-- <span class="iconfont uv-chatbubble-outline"></span> -->
        <svg aria-hidden="true">
          <use xlink:href="#icon-xiaoxi"></use>
        </svg>
        评论数量
      </div>
      <div class="message-tag">100</div>
    </section>
    <section>
      <div>
        <!-- <span class="iconfont uv-browsers-outline"></span> -->
        <svg aria-hidden="true">
          <use xlink:href="#icon-rili"></use>
        </svg>
        运行天数
      </div>
      <div class="message-tag">{{config.BlogTime | TimeDiffPipe }}</div>
    </section>
    <section>
      <div>
        <!-- <span class="iconfont uv-pulse-outline"></span> -->
        <svg aria-hidden="true">
          <use xlink:href="#icon-shijian"></use>
        </svg>
        最后活动
      </div>
      <div class="message-tag">{{config.ActiveTime}}</div>
    </section>
    <section>
      <div>
        <!-- <span class="iconfont uv-eye-outline"></span> -->
        <svg aria-hidden="true">
          <use xlink:href="#icon-biaoqing"></use>
        </svg>
        访问量
      </div>
      <div class="message-tag">{{config.BlogViewCount}}次</div>
    </section>
  </div>
</div>
