// my-app/src/app/blog/home/component/left-menus/avatar/avatar.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-avatar',
  templateUrl: './avatar.component.html',
  styleUrls: ['./avatar.component.less']
})
export class AvatarComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="avatar">
  <div class="avatar-img">
    <img
      src="https://gitee.com/Uvdream/images/raw/master/images/20200724164740.png"
      alt=""
    />
  </div>
  <div class="avatar-person">
    <div class="avatar-person-name">WangZhongJie</div>
    <div class="avatar-person-introduction">让技术产生价值</div>
  </div>
</div>

// web/src/layouts/components/left-menus/avatar.tsx
import React from 'react';
import './index.less';
const Avatar = () => {
  return (
    <div className="avatar">
      <div className="avatar-img">
        <img
          src="https://gitee.com/Uvdream/images/raw/master/images/20200724164740.png"
          alt=""
        />
      </div>
      <div className="avatar-person">
        <div className="avatar-person-name">wangzhongjie</div>
        <div className="avatar-person-introduction">让技术产生价值</div>
      </div>
    </div>
  );
};
export default Avatar;
