// web/src/app/blog/home/component/left-menus/navigation/navigation.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { ArticleCatalogService } from '@service/article-catalog.service';
interface MenuItem {
  title: string;
  id: number;
  icon: string;
  url: string;
}
@Component({
  selector: 'app-navigation',
  templateUrl: './navigation.component.html',
  styleUrls: ['./navigation.component.less'],
})
export class NavigationComponent implements OnInit {
  constructor(private router: Router, private catalogService: ArticleCatalogService,) { }
  public menus = [
    { title: '首页', id: 1, icon: 'uv-home-outline', url: '/home' },
    { title: '仓库', id: 2, icon: 'uv-git-merge-outline', url: '/github' },
    { title: '相册', id: 6, icon: 'uv-image-outline', url: '/photos' },
    { title: '归档', id: 3, icon: 'uv-file-tray-full-outline', url: '/archives' },
    { title: '留言', id: 4, icon: 'uv-at-sharp', url: '/comment' },
    { title: '关于', id: 5, icon: 'uv-cafe-outline', url: '/about' },
  ];
  public ActiveMenus = 1;
  ngOnInit(): void { }
  // tslint:disable-next-line:typedef
  navFunc(item: MenuItem) {
    this.ActiveMenus = item.id;
    this.router.navigate([item.url]);
    this.catalogService.SetCatLog()
  }
}

<div class="nav">
  <div class="nav-title">导航</div>
  <ul>
    <li *ngFor="let item of menus" (click)="navFunc(item)" [ngClass]="{active: ActiveMenus==item.id}">
      <!-- <span class="iconfont nav-icon" [ngClass]="item.icon"></span> -->
      <svg class="icon" aria-hidden="true">
        <use [attr.xlink:href]="'#'+item.icon"></use>
      </svg>
      <span> {{ item.title }}</span>
    </li>
  </ul>
</div>

// web/src/layouts/components/left-menus/navigation.tsx
import React, { useState } from 'react';
import "./index.less"
import { createFromIconfontCN } from '@ant-design/icons';
const IconFont = createFromIconfontCN({
    scriptUrl: '//at.alicdn.com/t/font_1762601_mkiqfjs1yth.js',
});
const Navigation = () => {
    const [menus] = useState([
        { title: "首页", id: 1, icon: "uv-home-outline" },
        { title: "仓库", id: 2, icon: "uv-git-merge-outline" },
        { title: "相册", id: 6, icon: "uv-image-outline" },
        { title: "归档", id: 3, icon: "uv-file-tray-full-outline" },
        { title: "留言", id: 4, icon: "uv-at-sharp" },
        { title: "关于", id: 5, icon: "uv-cafe-outline" },

    ])
    return (
        <nav className="nav">
            <div className="nav-title">导航</div>
            <ul>
                {
                    menus.map(item => {
                        return (
                            <li key={item.id}>
                                <IconFont type={item.icon} className="nav-icon" />
                                <span>{item.title}</span>
                            </li>
                        )
                    })
                }
            </ul>
        </nav>
    )
}
export default Navigation;
